export const MAIN = [
  { button: "basic" },
  { button: "dom" },
  { button: "methods" },
  { button: "math" },
  { button: "regexps" },
  { button: "events" },
  { button: "forms" },
  { button: "destruct" },
  { button: "classes" },
  { button: "oop" },
  { button: "webpack" },
  { button: "async" },
  { button: "react" },
  { button: "hooks" },
  { button: "state" },
  { button: "backend" },
  { button: "express&rest" },
  { button: "mongo" },
  { button: "auth" },
  { button: "security" },
  { button: "deploy" },
  { button: "tests" },
  { button: "about functions" },
  { button: "about oop" },
  { button: "data structures" },
  { button: "sort algorhitms" },
];
